using System.Text.Json;
using MassTransit;
using MediatR;
using Microsoft.Extensions.Logging;
using NotificationService.Application.CQRS.Command.Notification;
using NotificationService.Domain.Enums;
using SharedContracts.Events.Blog;
using SharedInfrastructure.Idempotency;

namespace NotificationService.Application.Consumers;

/// <summary>
/// Consumer cho <see cref="BlogGenerationStatusChangedEvent"/>:
/// Gửi InApp notification cho user đã yêu cầu generate blog (Manager/Admin)
/// khi AI hoàn thành (Draft) hoặc thất bại (GenerationFailed).
/// </summary>
public class BlogGenerationStatusConsumer : IConsumer<BlogGenerationStatusChangedEvent>
{
    private readonly IMediator _mediator;
    private readonly IInboxStore _inboxStore;
    private readonly ILogger<BlogGenerationStatusConsumer> _logger;

    public BlogGenerationStatusConsumer(IMediator mediator, IInboxStore inboxStore, ILogger<BlogGenerationStatusConsumer> logger)
    {
        _mediator = mediator;
        _inboxStore = inboxStore;
        _logger = logger;
    }

    public async Task Consume(ConsumeContext<BlogGenerationStatusChangedEvent> context)
    {
        await context.ProcessOnceAsync(_inboxStore, nameof(BlogGenerationStatusConsumer), async () =>
        {
            var evt = context.Message;

            var isSuccess = evt.Status == "Draft";
            var notificationType = isSuccess ? NotificationTypeEnum.BlogGenerationCompleted : NotificationTypeEnum.BlogGenerationFailed;

            var title = isSuccess
                ? "Blog created successfully"
                : "AI blog generation failed";

            // KHÔNG dán ErrorMessage (message exception .NET) vào Body: người đọc là Manager/Admin
            // chứ không phải người debug, và chuỗi kiểu "The request was canceled due to the
            // configured HttpClient.Timeout of 60 seconds elapsing." vừa không nói họ phải làm gì
            // vừa lộ chi tiết nội bộ. Diễn giải sang nguyên nhân + hành động tiếp theo;
            // message gốc đẩy xuống PayloadJson cho ai cần tra.
            var body = isSuccess
                ? $"The blog post \"{Truncate(evt.BlogTitle)}\" was successfully generated by AI and is now in Draft status. Please review and publish when ready."
                : $"The blog post \"{Truncate(evt.BlogTitle)}\" could not be generated: {DescribeFailure(evt.ErrorMessage)}";

            var cmd = new CreateNotificationCommand
            {
                UserId = evt.RequestedByUserId,
                Type = notificationType,
                Channel = NotificationChannelEnum.InApp,
                Title = title,
                Body = body,
                PayloadJson = JsonSerializer.Serialize(new
                {
                    blogPostId = evt.BlogPostId,
                    // Giữ nguyên message kỹ thuật ở đây — FE hiện trong mục "Dữ liệu kèm theo"
                    // (gập lại), ai cần tra vẫn có, người dùng thường không phải đọc.
                    errorMessage = isSuccess ? null : evt.ErrorMessage,
                }),
                EntityType = "BlogPost",
                EntityId = evt.BlogPostId,
            };

            var result = await _mediator.Send(cmd, context.CancellationToken);
            if (!result.IsSuccess)
            {
                _logger.LogWarning(
                    "Failed to create BlogGenerationStatus notification for BlogPostId={BlogPostId}: {Message}",
                    evt.BlogPostId, result.Message);
            }
        });
    }

    /// <summary>
    /// Quy message lỗi kỹ thuật về một câu người dùng hiểu được, kèm việc họ có thể làm tiếp.
    ///
    /// Nhận diện theo từ khoá vì lỗi đến từ nhiều nguồn (HttpClient, AI provider, chính service)
    /// và không có mã lỗi chung; không khớp mẫu nào thì trả câu chung chứ KHÔNG rơi về việc
    /// đọc nguyên message gốc.
    /// </summary>
    private static string DescribeFailure(string? errorMessage)
    {
        if (string.IsNullOrWhiteSpace(errorMessage))
            return "Unknown error. Please try generating it again.";

        var e = errorMessage.ToLowerInvariant();

        if (e.Contains("timeout") || e.Contains("canceled") || e.Contains("cancelled"))
            return "AI processing took too long and was stopped. Please try again, or shorten the source content if it is too long.";

        if (e.Contains("429") || e.Contains("rate limit") || e.Contains("quota"))
            return "The AI service is currently overloaded. Please try again in a few minutes.";

        if (e.Contains("unauthorized") || e.Contains("401") || e.Contains("api key") || e.Contains("forbidden") || e.Contains("403"))
            return "The connection to the AI service was refused. This requires an administrator to check the configuration.";

        if (e.Contains("connection") || e.Contains("socket") || e.Contains("host") || e.Contains("network"))
            return "Could not connect to the AI service. Please try again in a few minutes.";

        return "The AI service encountered an error while processing. Please try generating it again.";
    }

    private static string Truncate(string? text, int max = 100)
    {
        if (string.IsNullOrEmpty(text))
            return string.Empty;
        return text.Length > max ? text[..max] + "..." : text;
    }
}
