<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.9" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="Testcontainers" Version="4.14.0" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.14.0" />
    <PackageReference Include="xunit" Version="2.7.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../services/BatteryService/src/BatteryService.Infrastructure/BatteryService.Infrastructure.csproj" />
    <ProjectReference Include="../../services/NotificationService/src/NotificationService.Infrastructure/NotificationService.Infrastructure.csproj" />
    <ProjectReference Include="../../services/TicketService/src/TicketService.Infrastructure/TicketService.Infrastructure.csproj" />
    <ProjectReference Include="../../shared/src/SharedContracts/SharedContracts.csproj" />
    <ProjectReference Include="../../shared/src/SharedInfrastructure/SharedInfrastructure.csproj" />
  </ItemGroup>

</Project>
