<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TicketService.Domain\TicketService.Domain.csproj" />
        <ProjectReference Include="..\..\..\..\shared\src\SharedInfrastructure\SharedInfrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\shared\src\SharedKernels\SharedKernels.csproj" />
    <ProjectReference Include="..\..\..\..\shared\src\SharedContracts\SharedContracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CQRS\Command\" />
    <Folder Include="StateMachine\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.5.9" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0-rc.2.24473.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
