// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketService.Infrastructure.Persistence;

#nullable disable

namespace TicketService.Infrastructure.Migrations
{
    [DbContext(typeof(TicketDbContext))]
    [Migration("20260625063600_AddTicketAudit")]
    partial class AddTicketAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicketService.Domain.Entities.CustomerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Email");

                    b.HasIndex("Status");

                    b.ToTable("customer_accounts", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.KbArticleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<string>("ChangeDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("change_description");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DiagnosisSteps")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diagnosis_steps");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MajorVersion")
                        .HasColumnType("integer")
                        .HasColumnName("major_version");

                    b.Property<string>("ManagerRejectReason")
                        .HasColumnType("text")
                        .HasColumnName("manager_reject_reason");

                    b.Property<int>("MinorVersion")
                        .HasColumnType("integer")
                        .HasColumnName("minor_version");

                    b.Property<string>("RecommendedParts")
                        .HasColumnType("jsonb")
                        .HasColumnName("recommended_parts");

                    b.Property<string>("SolutionSteps")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solution_steps");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symptoms");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("MajorVersion");

                    b.HasIndex("ArticleId", "MajorVersion", "MinorVersion")
                        .IsUnique();

                    b.ToTable("kb_article_versions", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.KnowledgeBaseArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DiagnosisSteps")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diagnosis_steps");

                    b.Property<int>("HelpfulCount")
                        .HasColumnType("integer")
                        .HasColumnName("helpful_count");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsInternalOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("ManagerRejectReason")
                        .HasColumnType("text")
                        .HasColumnName("manager_reject_reason");

                    b.Property<Guid?>("PendingReviewBy")
                        .HasColumnType("uuid")
                        .HasColumnName("pending_review_by");

                    b.Property<string>("RecommendedParts")
                        .HasColumnType("jsonb")
                        .HasColumnName("recommended_parts");

                    b.Property<bool>("ReviewRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("review_required");

                    b.Property<string>("SolutionSteps")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solution_steps");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symptoms");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("knowledge_base_articles", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.MaintenanceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionsTaken")
                        .HasColumnType("text")
                        .HasColumnName("actions_taken");

                    b.Property<string>("AfterPhotosFileIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("after_photos_file_ids");

                    b.Property<string>("AttachmentFileIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attachment_file_ids");

                    b.Property<string>("BeforePhotosFileIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("before_photos_file_ids");

                    b.Property<DateTime?>("CheckInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_at");

                    b.Property<decimal?>("CheckInLatitude")
                        .HasColumnType("numeric")
                        .HasColumnName("check_in_latitude");

                    b.Property<decimal?>("CheckInLongitude")
                        .HasColumnType("numeric")
                        .HasColumnName("check_in_longitude");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DiagnosisDetails")
                        .HasColumnType("text")
                        .HasColumnName("diagnosis_details");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LogType")
                        .HasColumnType("integer")
                        .HasColumnName("log_type");

                    b.Property<string>("PartsUsed")
                        .HasColumnType("jsonb")
                        .HasColumnName("parts_used");

                    b.Property<string>("RelatedKbArticleIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("related_kb_article_ids");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text")
                        .HasColumnName("resolution_note");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LogType");

                    b.HasIndex("StaffId");

                    b.HasIndex("TicketId");

                    b.ToTable("maintenance_logs", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("idx_outbox_pending")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.SlaPauseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedByManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_manager_id");

                    b.Property<short?>("AutoResumeReason")
                        .HasColumnType("smallint")
                        .HasColumnName("auto_resume_reason");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool?>("IsApprovedByManager")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved_by_manager");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<Guid>("PausedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("paused_by_user_id");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("ResumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resumed_at");

                    b.Property<Guid?>("ResumedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resumed_by_user_id");

                    b.Property<Guid>("SlaTimerId")
                        .HasColumnType("uuid")
                        .HasColumnName("sla_timer_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SlaTimerId");

                    b.ToTable("sla_pause_events", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.SlaTimer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ApprovalRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("approval_required");

                    b.Property<DateTime?>("BreachAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("breach_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CurrentPauseStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_pause_started_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAutoResumeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_auto_resume_at");

                    b.Property<int>("MaxPauseEpisodes")
                        .HasColumnType("integer")
                        .HasColumnName("max_pause_episodes");

                    b.Property<int>("MaxTotalPauseMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("max_total_pause_minutes");

                    b.Property<DateTime>("OriginalDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_due_at");

                    b.Property<int>("PauseEpisodesCount")
                        .HasColumnType("integer")
                        .HasColumnName("pause_episodes_count");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<int>("TotalPausedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("total_paused_minutes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WarningSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("warning_sent_at");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("sla_timers", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.StaffAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_code");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<int>("MaxConcurrentTickets")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrent_tickets");

                    b.Property<string>("SkillCodes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("skill_codes");

                    b.Property<int>("SkillTier")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Email");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("staff_accounts", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_manager_id");

                    b.Property<Guid?>("AssignedStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_staff_id");

                    b.Property<Guid>("BatteryAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("battery_asset_id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("escalated_at");

                    b.Property<int?>("EscalationReason")
                        .HasColumnType("integer")
                        .HasColumnName("escalation_reason");

                    b.Property<int?>("ImpactScope")
                        .HasColumnType("integer")
                        .HasColumnName("impact_scope");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsIncident")
                        .HasColumnType("boolean")
                        .HasColumnName("is_incident");

                    b.Property<int>("Origin")
                        .HasColumnType("integer")
                        .HasColumnName("origin");

                    b.Property<Guid?>("OriginAlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_alert_id");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("RatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rated_at");

                    b.Property<short?>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<string>("RatingComment")
                        .HasColumnType("text")
                        .HasColumnName("rating_comment");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int>("ReopenCount")
                        .HasColumnType("integer")
                        .HasColumnName("reopen_count");

                    b.Property<string>("ResolutionSummary")
                        .HasColumnType("text")
                        .HasColumnName("resolution_summary");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_staff_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UrgencyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("urgency_level");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("BatteryAssetId");

                    b.HasIndex("Category");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.TicketActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<string>("ActorDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_display_name");

                    b.Property<int>("ActorRole")
                        .HasColumnType("integer")
                        .HasColumnName("actor_role");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("TicketId");

                    b.ToTable("ticket_activities", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.TicketAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("TicketId");

                    b.ToTable("ticket_attachments", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.TicketAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_category");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_code");

                    b.Property<Guid?>("ActorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_account_id");

                    b.Property<string>("ActorDisplay")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("actor_display");

                    b.Property<string>("ActorIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor_ip");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actor_role");

                    b.Property<string>("ActorUserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("actor_user_agent");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("error_code");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("service_name");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("TargetDisplay")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("target_display");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_ticket_audit_logs_correlation");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_ticket_audit_logs_event_id");

                    b.HasIndex("ActionCode", "CreatedAt")
                        .HasDatabaseName("ix_ticket_audit_logs_action");

                    b.HasIndex("TargetId", "CreatedAt")
                        .HasDatabaseName("ix_ticket_audit_logs_target");

                    b.ToTable("ticket_audit_logs", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.TicketAuditOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_ticket_audit_outbox_event_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_ticket_audit_outbox_pending")
                        .HasFilter("status = 1");

                    b.ToTable("ticket_audit_outbox", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttachmentFileIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attachment_file_ids");

                    b.Property<string>("AuthorDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("author_display_name");

                    b.Property<int>("AuthorRole")
                        .HasColumnType("integer")
                        .HasColumnName("author_role");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("TicketId");

                    b.ToTable("ticket_comments", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.TicketKbReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("KbArticleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kb_article_code");

                    b.Property<Guid>("KbArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("kb_article_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("integer")
                        .HasColumnName("reference_type");

                    b.Property<Guid>("ReferencedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("referenced_by_user_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TicketId", "KbArticleId", "ReferenceType")
                        .IsUnique();

                    b.ToTable("ticket_kb_references", (string)null);
                });

            modelBuilder.Entity("TicketService.Infrastructure.Sagas.AlertTicketSagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<decimal?>("ActualValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("actual_value");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<int>("AnomalyType")
                        .HasColumnType("integer")
                        .HasColumnName("anomaly_type");

                    b.Property<string>("AssetSerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("asset_serial_number");

                    b.Property<Guid?>("BatteryAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("battery_asset_id");

                    b.Property<decimal?>("CellVoltageDeltaMv")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("cell_voltage_delta_mv");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_state");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid?>("EnvironmentalIncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmental_incident_id");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailedAtStage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failed_at_stage");

                    b.Property<string>("FailureErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("failure_error_code");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<decimal?>("InternalResistanceMilliohm")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("internal_resistance_milliohm");

                    b.Property<Guid?>("PendingTimeoutTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("pending_timeout_token_id");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<decimal?>("ThresholdValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("threshold_value");

                    b.Property<string>("TicketCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ticket_code");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<bool>("TicketIsReused")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ticket_is_reused");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("CorrelationId");

                    b.HasIndex("AlertId")
                        .IsUnique()
                        .HasDatabaseName("ux_alert_ticket_saga_states_alert_id");

                    b.HasIndex("BatteryAssetId")
                        .HasDatabaseName("ix_alert_ticket_saga_states_battery_asset_id");

                    b.HasIndex("CurrentState")
                        .HasDatabaseName("ix_alert_ticket_saga_states_current_state");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_alert_ticket_saga_states_started_at");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_alert_ticket_saga_states_ticket_id");

                    b.ToTable("alert_ticket_saga_states", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.KbArticleVersion", b =>
                {
                    b.HasOne("TicketService.Domain.Entities.KnowledgeBaseArticle", "Article")
                        .WithMany("Versions")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("TicketService.Domain.Entities.MaintenanceLog", b =>
                {
                    b.HasOne("TicketService.Domain.Entities.Ticket", "Ticket")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TicketService.Domain.Entities.SlaPauseEvent", b =>
                {
                    b.HasOne("TicketService.Domain.Entities.SlaTimer", "SlaTimer")
                        .WithMany()
                        .HasForeignKey("SlaTimerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SlaTimer");
                });

            modelBuilder.Entity("TicketService.Domain.Entities.SlaTimer", b =>
                {
                    b.HasOne("TicketService.Domain.Entities.Ticket", "Ticket")
                        .WithOne("SlaTimer")
                        .HasForeignKey("TicketService.Domain.Entities.SlaTimer", "TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TicketService.Domain.Entities.TicketActivity", b =>
                {
                    b.HasOne("TicketService.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Activities")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TicketService.Domain.Entities.TicketAttachment", b =>
                {
                    b.HasOne("TicketService.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TicketService.Domain.Entities.TicketComment", b =>
                {
                    b.HasOne("TicketService.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TicketService.Domain.Entities.TicketKbReference", b =>
                {
                    b.HasOne("TicketService.Domain.Entities.Ticket", null)
                        .WithMany("KbReferences")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketService.Domain.Entities.KnowledgeBaseArticle", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("TicketService.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("KbReferences");

                    b.Navigation("MaintenanceLogs");

                    b.Navigation("SlaTimer");
                });
#pragma warning restore 612, 618
        }
    }
}
