// <auto-generated />
using System;
using BatteryService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BatteryService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260612111925_AddIotDeviceManagement")]
    partial class AddIotDeviceManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BatteryService.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by_user_id");

                    b.Property<decimal?>("ActualValue")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("actual_value");

                    b.Property<int>("AnomalyType")
                        .HasColumnType("integer")
                        .HasColumnName("anomaly_type");

                    b.Property<Guid?>("BatteryAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("battery_asset_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DedupWindowEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dedup_window_end_utc");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid?>("EnvironmentalIncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environmental_incident_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("MergedIntoAlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_alert_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<decimal?>("ThresholdValue")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("threshold_value");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BatteryAssetId");

                    b.HasIndex("EnvironmentalIncidentId");

                    b.HasIndex("MergedIntoAlertId");

                    b.HasIndex("Severity");

                    b.HasIndex("SiteId");

                    b.HasIndex("Status");

                    b.HasIndex("BatteryAssetId", "AnomalyType", "Status", "DedupWindowEndUtc");

                    b.ToTable("alerts", null, t =>
                        {
                            t.HasCheckConstraint("ck_alerts_asset_or_site_required", "battery_asset_id IS NOT NULL OR site_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.AmbientReading", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<decimal>("AmbientTemperature")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("ambient_temperature_celsius");

                    b.Property<decimal?>("Humidity")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("humidity_percent");

                    b.Property<decimal?>("SolarIrradiance")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("solar_irradiance_wm2");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("source");

                    b.Property<string>("SourceDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_device_id");

                    b.HasKey("Time", "SiteId");

                    b.HasIndex("SiteId", "Time")
                        .HasDatabaseName("ix_ambient_readings_site_time");

                    b.ToTable("ambient_readings", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.AmbientThresholdConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ComboHumidityThreshold")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("combo_humidity_threshold");

                    b.Property<decimal?>("ComboTempThreshold")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("combo_temp_threshold");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<decimal?>("HighAmbientTempCritical")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("high_ambient_temp_critical");

                    b.Property<decimal?>("HighAmbientTempWarning")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("high_ambient_temp_warning");

                    b.Property<decimal?>("HighHumidityCritical")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("high_humidity_critical");

                    b.Property<decimal?>("HighHumidityWarning")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("high_humidity_warning");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .IsUnique()
                        .HasDatabaseName("ux_ambient_threshold_configs_site_active")
                        .HasFilter("is_deleted = false AND enabled = true");

                    b.ToTable("ambient_threshold_configs", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.BatteryAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatteryTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("battery_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("install_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastSensorReadingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sensor_reading_at");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("serial_number");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("WarrantyEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("warranty_end_date");

                    b.Property<int>("WarrantyStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("warranty_status");

                    b.HasKey("Id");

                    b.HasIndex("BatteryTypeId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LastSensorReadingAt");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("is_deleted = false");

                    b.HasIndex("SiteId");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "IsDeleted", "Status");

                    b.HasIndex("SiteId", "IsDeleted", "Status");

                    b.ToTable("battery_assets", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.BatteryType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Chemistry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("chemistry");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("manufacturer");

                    b.Property<int>("MaxCycleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2000)
                        .HasColumnName("max_cycle_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("NominalCapacityAh")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("nominal_capacity_ah");

                    b.Property<decimal>("NominalVoltage")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("nominal_voltage");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Chemistry");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("is_deleted = false");

                    b.ToTable("battery_types", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.CustomerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("is_deleted = false");

                    b.HasIndex("IsActive", "IsDeleted");

                    b.ToTable("customer_accounts", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.EnvironmentalIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<DateTime?>("FalseAlarmAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("false_alarm_at");

                    b.Property<Guid?>("FalseAlarmBy")
                        .HasColumnType("uuid")
                        .HasColumnName("false_alarm_by");

                    b.Property<string>("FalseAlarmReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("false_alarm_reason");

                    b.Property<int>("IncidentType")
                        .HasColumnType("integer")
                        .HasColumnName("incident_type");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("ReportedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("reported_by");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<int>("Severity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("severity");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt")
                        .HasDatabaseName("ix_environmental_incidents_detected_at");

                    b.HasIndex("SiteId", "Status")
                        .HasDatabaseName("ix_environmental_incidents_site_status");

                    b.ToTable("environmental_incidents", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.IotDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("api_key_hash");

                    b.Property<DateTime>("ApiKeyIssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("api_key_issued_at");

                    b.Property<string>("ApiKeyLastFour")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("api_key_last_four");

                    b.Property<DateTime?>("ApiKeyRevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("api_key_revoked_at");

                    b.Property<int>("ApiKeyScopes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(11)
                        .HasColumnName("api_key_scopes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrentFirmwareVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("current_firmware_version");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("HardwareRevision")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hardware_revision");

                    b.Property<int>("HeartbeatIntervalSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("heartbeat_interval_seconds");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<double?>("LastClockSkewSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("last_clock_skew_seconds");

                    b.Property<DateTime?>("LastOfflineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_offline_at");

                    b.Property<DateTime?>("LastProvisionedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_provisioned_at");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetFirmwareReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_firmware_release_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .HasDatabaseName("idx_iot_devices_api_key_hash");

                    b.HasIndex("DeviceCode")
                        .IsUnique()
                        .HasDatabaseName("idx_iot_devices_device_code")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("idx_iot_devices_site");

                    b.HasIndex("TargetFirmwareReleaseId");

                    b.HasIndex("Status", "LastSeenAt")
                        .HasDatabaseName("idx_iot_devices_status_last_seen");

                    b.ToTable("iot_devices", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.IotDeviceCalibration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BatteryAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("battery_asset_id");

                    b.Property<DateTime>("CalibratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calibrated_at");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IotDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("iot_device_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<decimal>("Offset")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("offset_value");

                    b.Property<decimal>("Scale")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasDefaultValue(1m)
                        .HasColumnName("scale");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IotDeviceId", "Channel", "BatteryAssetId")
                        .HasDatabaseName("idx_iot_calibrations_lookup")
                        .HasFilter("is_deleted = false");

                    b.ToTable("iot_device_calibrations", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.IotDeviceHeartbeat", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("IotDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("iot_device_id");

                    b.Property<double?>("ClockSkewSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("clock_skew_seconds");

                    b.Property<DateTime?>("DeviceTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_timestamp");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("firmware_version");

                    b.Property<decimal?>("FreeMemoryPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("free_memory_percent");

                    b.Property<int?>("QueuedReadingCount")
                        .HasColumnType("integer")
                        .HasColumnName("queued_reading_count");

                    b.Property<int?>("RssiDbm")
                        .HasColumnType("integer")
                        .HasColumnName("rssi_dbm");

                    b.Property<long?>("UptimeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("uptime_seconds");

                    b.HasKey("Time", "IotDeviceId");

                    b.HasIndex("IotDeviceId", "Time")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_iot_heartbeats_device_time");

                    b.ToTable("iot_device_heartbeats", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.IotFirmwareRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ArtifactSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("artifact_size_bytes");

                    b.Property<string>("ArtifactUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("artifact_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("HardwareRevision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hardware_revision");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("ReleaseNotes")
                        .HasColumnType("text")
                        .HasColumnName("release_notes");

                    b.Property<string>("Sha256Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256_checksum");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Version", "HardwareRevision")
                        .IsUnique()
                        .HasDatabaseName("idx_iot_firmware_version_hw")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("HardwareRevision", "IsPublished", "IsArchived")
                        .HasDatabaseName("idx_iot_firmware_rollout");

                    b.ToTable("iot_firmware_releases", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.IotFirmwareUpdateLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("BytesDownloaded")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_downloaded");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("FromVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("from_version");

                    b.Property<Guid>("IotDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("iot_device_id");

                    b.Property<Guid>("IotFirmwareReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("iot_firmware_release_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<string>("ToVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("to_version");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IotFirmwareReleaseId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_iot_firmware_log_status");

                    b.HasIndex("IotDeviceId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_iot_firmware_log_device_time");

                    b.ToTable("iot_firmware_update_logs", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.NoiseBreachEvent", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("BatteryAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("battery_asset_id");

                    b.Property<int>("AnomalyType")
                        .HasColumnType("integer")
                        .HasColumnName("anomaly_type");

                    b.Property<decimal>("ActualValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("actual_value");

                    b.Property<Guid?>("PromotedToAlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("promoted_to_alert_id");

                    b.Property<int>("SourceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("source_type");

                    b.Property<decimal>("ThresholdValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("threshold_value");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.HasKey("Time", "BatteryAssetId", "AnomalyType");

                    b.HasIndex("PromotedToAlertId")
                        .HasDatabaseName("ix_noise_breach_events_promoted_alert")
                        .HasFilter("promoted_to_alert_id IS NOT NULL");

                    b.HasIndex("BatteryAssetId", "AnomalyType", "Time")
                        .HasDatabaseName("ix_noise_breach_events_asset_type_time");

                    b.ToTable("noise_breach_events", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("idx_outbox_pending")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.SensorReading", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("BatteryAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("battery_asset_id");

                    b.Property<string>("BmsErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("bms_error_code");

                    b.Property<decimal?>("CellVoltageDeltaMv")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("cell_voltage_delta_mv");

                    b.Property<int?>("ChargingState")
                        .HasColumnType("integer")
                        .HasColumnName("charging_state");

                    b.Property<decimal>("Current")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("current");

                    b.Property<int?>("CycleCount")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_count");

                    b.Property<decimal?>("InternalResistanceMilliohm")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("internal_resistance_milliohm");

                    b.Property<string>("SensorSourceCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sensor_source_code");

                    b.Property<decimal>("SocPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("soc_percent");

                    b.Property<decimal?>("SohPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("soh_percent");

                    b.Property<string>("SourceDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_device_id");

                    b.Property<int>("SourceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("source_type");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<decimal>("Voltage")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("voltage");

                    b.HasKey("Time", "BatteryAssetId");

                    b.HasIndex("BatteryAssetId", "Time")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_sensor_readings_asset_time");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("ContactPersonName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("contact_person_name");

                    b.Property<string>("ContactPersonPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_person_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("install_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "Name")
                        .IsUnique()
                        .HasFilter("is_deleted = false");

                    b.HasIndex("CustomerId", "IsDeleted", "Status");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.ThresholdConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatteryTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("battery_type_id");

                    b.Property<decimal?>("CellVoltageDeltaMaxMv")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("cell_voltage_delta_max_mv");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("CurrentMaxCharge")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("current_max_charge");

                    b.Property<decimal?>("CurrentMaxDischarge")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("current_max_discharge");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<decimal?>("InternalResistanceMaxMilliohm")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("internal_resistance_max_milliohm");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("NoiseSuppressionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("noise_suppression_count");

                    b.Property<bool>("NoiseSuppressionEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("noise_suppression_enabled");

                    b.Property<int>("NoiseSuppressionWindowHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(24)
                        .HasColumnName("noise_suppression_window_hours");

                    b.Property<decimal>("SocCriticalThreshold")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("soc_critical_threshold");

                    b.Property<decimal>("SocWarningThreshold")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("soc_warning_threshold");

                    b.Property<decimal?>("SohCriticalThreshold")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("soh_critical_threshold");

                    b.Property<decimal?>("SohWarningThreshold")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("soh_warning_threshold");

                    b.Property<decimal>("TemperatureMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature_max");

                    b.Property<decimal>("TemperatureMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature_min");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("VoltageMax")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("voltage_max");

                    b.Property<decimal>("VoltageMin")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("voltage_min");

                    b.HasKey("Id");

                    b.HasIndex("BatteryTypeId");

                    b.HasIndex("BatteryTypeId", "IsActive")
                        .IsUnique()
                        .HasFilter("is_active = true AND is_deleted = false");

                    b.ToTable("threshold_configs", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.Alert", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.BatteryAsset", "BatteryAsset")
                        .WithMany("Alerts")
                        .HasForeignKey("BatteryAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BatteryService.Domain.Entities.EnvironmentalIncident", "EnvironmentalIncident")
                        .WithMany("Alerts")
                        .HasForeignKey("EnvironmentalIncidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BatteryService.Domain.Entities.Alert", "MergedIntoAlert")
                        .WithMany("MergedAlerts")
                        .HasForeignKey("MergedIntoAlertId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BatteryService.Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BatteryAsset");

                    b.Navigation("EnvironmentalIncident");

                    b.Navigation("MergedIntoAlert");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.AmbientReading", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.AmbientThresholdConfig", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.BatteryAsset", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.BatteryType", "BatteryType")
                        .WithMany("Assets")
                        .HasForeignKey("BatteryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BatteryService.Domain.Entities.Site", "Site")
                        .WithMany("BatteryAssets")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BatteryType");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.EnvironmentalIncident", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.IotDevice", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BatteryService.Domain.Entities.IotFirmwareRelease", "TargetFirmwareRelease")
                        .WithMany()
                        .HasForeignKey("TargetFirmwareReleaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Site");

                    b.Navigation("TargetFirmwareRelease");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.IotDeviceCalibration", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.IotDevice", "IotDevice")
                        .WithMany("Calibrations")
                        .HasForeignKey("IotDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IotDevice");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.IotDeviceHeartbeat", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.IotDevice", "IotDevice")
                        .WithMany("Heartbeats")
                        .HasForeignKey("IotDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IotDevice");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.IotFirmwareUpdateLog", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.IotDevice", "IotDevice")
                        .WithMany("FirmwareUpdateLogs")
                        .HasForeignKey("IotDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BatteryService.Domain.Entities.IotFirmwareRelease", "IotFirmwareRelease")
                        .WithMany("UpdateLogs")
                        .HasForeignKey("IotFirmwareReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IotDevice");

                    b.Navigation("IotFirmwareRelease");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.NoiseBreachEvent", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.BatteryAsset", "BatteryAsset")
                        .WithMany()
                        .HasForeignKey("BatteryAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BatteryAsset");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.SensorReading", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.BatteryAsset", "BatteryAsset")
                        .WithMany("SensorReadings")
                        .HasForeignKey("BatteryAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BatteryAsset");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.ThresholdConfig", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.BatteryType", "BatteryType")
                        .WithMany("ThresholdConfigs")
                        .HasForeignKey("BatteryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BatteryType");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.Alert", b =>
                {
                    b.Navigation("MergedAlerts");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.BatteryAsset", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.BatteryType", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("ThresholdConfigs");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.EnvironmentalIncident", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.IotDevice", b =>
                {
                    b.Navigation("Calibrations");

                    b.Navigation("FirmwareUpdateLogs");

                    b.Navigation("Heartbeats");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.IotFirmwareRelease", b =>
                {
                    b.Navigation("UpdateLogs");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.Site", b =>
                {
                    b.Navigation("BatteryAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
