// <auto-generated />
using System;
using BatteryService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BatteryService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514014339_InitBatteryDb")]
    partial class InitBatteryDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BatteryService.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by_user_id");

                    b.Property<decimal>("ActualValue")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("actual_value");

                    b.Property<int>("AnomalyType")
                        .HasColumnType("integer")
                        .HasColumnName("anomaly_type");

                    b.Property<Guid>("BatteryAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("battery_asset_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DedupWindowEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dedup_window_end_utc");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("MergedIntoAlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_alert_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<decimal>("ThresholdValue")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("threshold_value");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BatteryAssetId");

                    b.HasIndex("MergedIntoAlertId");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.HasIndex("BatteryAssetId", "AnomalyType", "Status", "DedupWindowEndUtc");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.BatteryAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatteryTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("battery_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("install_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastSensorReadingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sensor_reading_at");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("serial_number");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("WarrantyEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("warranty_end_date");

                    b.Property<int>("WarrantyStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("warranty_status");

                    b.HasKey("Id");

                    b.HasIndex("BatteryTypeId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LastSensorReadingAt");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("is_deleted = false");

                    b.HasIndex("Status");

                    b.HasIndex("CustomerId", "IsDeleted", "Status");

                    b.ToTable("battery_assets", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.BatteryType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Chemistry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("chemistry");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("manufacturer");

                    b.Property<int>("MaxCycleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2000)
                        .HasColumnName("max_cycle_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("NominalCapacityAh")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("nominal_capacity_ah");

                    b.Property<decimal>("NominalVoltage")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("nominal_voltage");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Chemistry");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("is_deleted = false");

                    b.ToTable("battery_types", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.SensorReading", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("BatteryAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("battery_asset_id");

                    b.Property<decimal>("Current")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("current");

                    b.Property<int?>("CycleCount")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_count");

                    b.Property<decimal>("SocPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("soc_percent");

                    b.Property<string>("SourceDeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_device_id");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature");

                    b.Property<decimal>("Voltage")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("voltage");

                    b.HasKey("Time", "BatteryAssetId");

                    b.HasIndex("BatteryAssetId", "Time")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_sensor_readings_asset_time");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.ThresholdConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatteryTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("battery_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("CurrentMaxCharge")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("current_max_charge");

                    b.Property<decimal?>("CurrentMaxDischarge")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("current_max_discharge");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("SocCriticalThreshold")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("soc_critical_threshold");

                    b.Property<decimal>("SocWarningThreshold")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("soc_warning_threshold");

                    b.Property<decimal>("TemperatureMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature_max");

                    b.Property<decimal>("TemperatureMin")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("temperature_min");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("VoltageMax")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("voltage_max");

                    b.Property<decimal>("VoltageMin")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("voltage_min");

                    b.HasKey("Id");

                    b.HasIndex("BatteryTypeId");

                    b.HasIndex("BatteryTypeId", "IsActive")
                        .IsUnique()
                        .HasFilter("is_active = true AND is_deleted = false");

                    b.ToTable("threshold_configs", (string)null);
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.Alert", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.BatteryAsset", "BatteryAsset")
                        .WithMany("Alerts")
                        .HasForeignKey("BatteryAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BatteryService.Domain.Entities.Alert", "MergedIntoAlert")
                        .WithMany("MergedAlerts")
                        .HasForeignKey("MergedIntoAlertId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BatteryAsset");

                    b.Navigation("MergedIntoAlert");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.BatteryAsset", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.BatteryType", "BatteryType")
                        .WithMany("Assets")
                        .HasForeignKey("BatteryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BatteryType");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.SensorReading", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.BatteryAsset", "BatteryAsset")
                        .WithMany("SensorReadings")
                        .HasForeignKey("BatteryAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BatteryAsset");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.ThresholdConfig", b =>
                {
                    b.HasOne("BatteryService.Domain.Entities.BatteryType", "BatteryType")
                        .WithMany("ThresholdConfigs")
                        .HasForeignKey("BatteryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BatteryType");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.Alert", b =>
                {
                    b.Navigation("MergedAlerts");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.BatteryAsset", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("BatteryService.Domain.Entities.BatteryType", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("ThresholdConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
