namespace TicketService.Domain.Enums;

/// <summary>Các hành động ghi nhận trong lịch sử (Timeline) của Ticket.</summary>
public enum ActivityActionEnum
{
    Created = 1,
    StatusChanged = 2,
    PriorityAssigned = 3,
    StaffAssigned = 4,
    StaffReassigned = 5,
    Chatted = 6,
    MaintenanceLogged = 7,
    AttachmentAdded = 8,
    SlaPaused = 9,
    SlaResumed = 10,
    SlaWarning = 11,
    SlaBreached = 12,
    EscalationRequested = 13,
    Escalated = 14,
    IncidentDeclared = 15,
    Resolved = 16,
    Approved = 17,
    Rejected = 18,
    Rated = 19,
    Reopened = 20,
    ResolvedByEscalatedStaff = 21,
    Closed = 22,
    ChatEdited = 23,
    ChatDeleted = 24,
    ChatRestored = 25,
    ChatReplied = 26,
    ChatPinned = 27,
    ChatUnpinned = 28,
    ChatFlagged = 29,
    RatingRequested = 30,
    ParticipantAdded = 31,
    ParticipantRemoved = 32,
    ParticipantRoleChanged = 33,
    IncidentDeclassified = 34,
    PeriodicMaintenanceScheduleChanged = 35
}
