<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="AWSSDK.S3" Version="4.0.23" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\shared\src\SharedInfrastructure\SharedInfrastructure.csproj" />
      <ProjectReference Include="..\FileStorageService.Application\FileStorageService.Application.csproj" />
    </ItemGroup>

</Project>
